name: fluid
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.PORTFOLIO}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git init
          git config --global user.email openhouseparty28@gmail.com
          git config --global user.name MangoStick
          git status
          git remote add origin https://${{secrets.PORTFOLIO}}@github.com/MangoStick/FluidPopUp.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
